-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 11:40:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`pizza` (
  `idpizza` INT NOT NULL,
  PRIMARY KEY (`idpizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`categoria` (
  `idcategoria` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NULL,
  `pizza_idpizza` INT NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_pizza1_idx` (`pizza_idpizza` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `Pizzeria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`producte` (
  `idproducte` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NULL,
  `descripció` VARCHAR(45) NULL,
  `Imatge` VARCHAR(45) NULL,
  `preu` DOUBLE NULL,
  `categoria_idcategoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idproducte`),
  INDEX `fk_producte_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_producte_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `Pizzeria`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`comanda` (
  `idcomanda` INT UNSIGNED NOT NULL,
  `data` DATE NULL,
  `repartimentdomicili` TINYINT NULL,
  `quantitat` INT NULL,
  `preutotal` DOUBLE NULL,
  `producte_idproducte` INT NOT NULL,
  PRIMARY KEY (`idcomanda`),
  INDEX `fk_comanda_producte1_idx` (`producte_idproducte` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_producte1`
    FOREIGN KEY (`producte_idproducte`)
    REFERENCES `Pizzeria`.`producte` (`idproducte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`client` (
  `idclient` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognoms` VARCHAR(45) NULL,
  `adreça` VARCHAR(45) NULL,
  `codi_postal` INT(5) NULL,
  `localitat` VARCHAR(45) NULL,
  `província` VARCHAR(45) NULL,
  `telèfon` INT(9) NULL,
  `comanda_idcomanda` INT NOT NULL,
  PRIMARY KEY (`idclient`),
  INDEX `fk_client_comanda_idx` (`comanda_idcomanda` ASC) VISIBLE,
  CONSTRAINT `fk_client_comanda`
    FOREIGN KEY (`comanda_idcomanda`)
    REFERENCES `Pizzeria`.`comanda` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`empleat` (
  `idempleat` INT UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognoms` VARCHAR(45) NULL,
  `NIF` VARCHAR(45) NULL,
  `telèfon` INT NULL,
  `cuiner` TINYINT NULL,
  PRIMARY KEY (`idempleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`botiga` (
  `idbotiga` INT NOT NULL,
  `comanda_idcomanda` INT UNSIGNED NOT NULL,
  `adreça` VARCHAR(45) NULL,
  `codi_postal` INT NULL,
  `localitat` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `empleat_idempleat` INT NOT NULL,
  PRIMARY KEY (`idbotiga`),
  INDEX `fk_botiga_comanda1_idx` (`comanda_idcomanda` ASC) VISIBLE,
  INDEX `fk_botiga_empleat1_idx` (`empleat_idempleat` ASC) VISIBLE,
  CONSTRAINT `fk_botiga_comanda1`
    FOREIGN KEY (`comanda_idcomanda`)
    REFERENCES `Pizzeria`.`comanda` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_botiga_empleat1`
    FOREIGN KEY (`empleat_idempleat`)
    REFERENCES `Pizzeria`.`empleat` (`idempleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
