-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 11:01:30 2022
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Culdampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Culdampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Culdampolla` ;
USE `Culdampolla` ;

-- -----------------------------------------------------
-- Table `Culdampolla`.`Proveïdor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Culdampolla`.`Proveïdor` (
  `Id` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nom` VARCHAR(50) NULL,
  `Adreça` VARCHAR(100) NULL,
  `Telèfon` INT(9) NULL,
  `Fax` INT(9) NULL,
  `NIF` VARCHAR(9) NULL,
  PRIMARY KEY (`Id`));


-- -----------------------------------------------------
-- Table `Culdampolla`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Culdampolla`.`Marca` (
  `Id_Marca` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nom` VARCHAR(45) NULL,
  `Proveïdor_Id` INT NOT NULL,
  PRIMARY KEY (`Id_Marca`),
  INDEX `fk_Marca_Proveïdor_idx` (`Proveïdor_Id` ASC),
  CONSTRAINT `fk_Marca_Proveïdor`
    FOREIGN KEY (`Proveïdor_Id`)
    REFERENCES `Culdampolla`.`Proveïdor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culdampolla`.`Montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Culdampolla`.`Montura` (
  `idMontura` INT NOT NULL,
  `Tipus` VARCHAR(45) NULL,
  PRIMARY KEY (`idMontura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culdampolla`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Culdampolla`.`Clients` (
  `Id_Client` INT GENERATED ALWAYS AS () VIRTUAL,
  `Nom` VARCHAR(45) NULL,
  `Adreça` TIMESTAMP NULL,
  `Telèfon` TIMESTAMP NULL,
  `Email` VARCHAR(45) NULL,
  `Data_Registre` DATE NULL,
  `Id_Recomanat` INT NOT NULL,
  PRIMARY KEY (`Id_Client`),
  INDEX `Client_Id_idx` (`Id_Recomanat` ASC),
  CONSTRAINT `Client_Id`
    FOREIGN KEY (`Id_Recomanat`)
    REFERENCES `Culdampolla`.`Clients` (`Id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Culdampolla`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Culdampolla`.`Empleat` (
  `idEmpleat` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Cognoms` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Culdampolla`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Culdampolla`.`Ulleres` (
  `Id_Ulleres` INT GENERATED ALWAYS AS () VIRTUAL,
  `Marca_Id` INT NOT NULL,
  `Graduació esq` INT NULL,
  `Graduació dret` INT NULL,
  `Id_Tipus Montura` INT NOT NULL,
  `Color Muntura` VARCHAR(45) NULL,
  `Color Vidre` VARCHAR(45) NULL,
  `Preu` FLOAT NULL,
  `Client_Id` INT NOT NULL,
  `Empleat_Id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Empleat_Id`),
  INDEX `Id_Ulleres_idx` (`Marca_Id` ASC),
  INDEX `Client_Id_idx` (`Client_Id` ASC),
  INDEX `IdMontura_idx` (`Id_Tipus Montura` ASC),
  CONSTRAINT `Id_Ulleres`
    FOREIGN KEY (`Marca_Id`)
    REFERENCES `Culdampolla`.`Marca` (`Id_Marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdMontura`
    FOREIGN KEY (`Id_Tipus Montura`)
    REFERENCES `Culdampolla`.`Montura` (`idMontura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Client_Id`
    FOREIGN KEY (`Client_Id`)
    REFERENCES `Culdampolla`.`Clients` (`Id_Client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Empleat_Id`
    FOREIGN KEY (`Id_Ulleres`)
    REFERENCES `Culdampolla`.`Empleat` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
